// Zellij type definitions for the MCP server

export interface ZellijSession {
  name: string;
  created: string;
  attached: boolean;
  tabs?: ZellijTab[];
}

export interface ZellijTab {
  name: string;
  active: boolean;
  panes?: ZellijPane[];
}

export interface ZellijPane {
  id: string;
  title?: string;
  command?: string;
  cwd?: string;
  focused: boolean;
}

export interface ZellijPlugin {
  id: string;
  name: string;
  url: string;
  configuration?: Record<string, any>;
  running: boolean;
}

export interface ZellijLayout {
  name: string;
  description?: string;
  tabs: Array<{
    name?: string;
    panes: Array<{
      split_direction?: 'horizontal' | 'vertical';
      parts?: any[];
    }>;
  }>;
}

export interface PipeOptions {
  name?: string;
  plugin?: string;
  args?: string;
  configuration?: Record<string, any>;
  forceLaunch?: boolean;
  skipCache?: boolean;
  floating?: boolean;
  inPlace?: boolean;
  cwd?: string;
  title?: string;
}

export interface PluginLaunchOptions {
  url: string;
  configuration?: Record<string, any>;
  floating?: boolean;
  inPlace?: boolean;
  skipCache?: boolean;
  width?: string;
  height?: string;
  x?: string;
  y?: string;
  pinned?: boolean;
}

export interface SessionExport {
  name: string;
  layout: ZellijLayout;
  created: string;
  metadata?: Record<string, any>;
}

export interface ZellijCommand {
  command: string;
  args: string[];
  session?: string;
  cwd?: string;
  timeout?: number;
}

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  sanitized?: any;
}

// Windows-MCP integration (CursorTouch/Windows-MCP, launched via `uvx windows-mcp`).
// Only meaningful when the host platform is Windows.
export type WindowsMCPTransport = 'streamable-http' | 'sse';

export interface WindowsMCPConfig {
  // streamable-http is the secure default (the MCP spec deprecated the SSE
  // transport in favour of Streamable HTTP). sse is kept as a fallback.
  transport: WindowsMCPTransport;
  host: string;
  port: number;
  // Bearer token sent on every HTTP request. Generated by `windows-mcp auth`.
  authKey?: string;
  // Comma-separated CIDR/IP allowlist passed through to Windows-MCP.
  ipAllowlist?: string;
  // Optional explicit TLS material; when omitted the config.toml written by
  // `windows-mcp auth --with-tls` (mkcert-preferred) is used instead.
  certFile?: string;
  keyFile?: string;
  // When true, register a persistent scheduled task via `windows-mcp install`.
  installAsTask?: boolean;
}

export interface WindowsMCPStatus {
  running: boolean;
  pid?: number;
  host: string;
  port: number;
  transport: WindowsMCPTransport;
  tls: boolean;
  // Streamable HTTP exposes /mcp/, SSE exposes /sse.
  url: string;
  message?: string;
}

export interface ZellijMetrics {
  sessionsCount: number;
  activeTabsCount: number;
  activePanesCount: number;
  pluginsCount: number;
  memoryUsage?: string;
  uptime?: string;
}

// Tool response types
export interface ToolResponse {
  content: Array<{
    type: 'text';
    text: string;
  }>;
}

// Error types
export class ZellijError extends Error {
  constructor(message: string, public code?: string) {
    super(message);
    this.name = 'ZellijError';
  }
}

export class ValidationError extends Error {
  constructor(message: string, public field?: string) {
    super(message);
    this.name = 'ValidationError';
  }
}

export class SecurityError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'SecurityError';
  }
}